[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "02"
path = "02/02.rs"

[dependencies]
enum-map = "2.7.3"
nom = "7.1.3"
